version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: pedidocerto
      DB_USERNAME: homestead
      DB_PASSWORD: secret
    command: >
      bash -c "
        echo 'Rodando composer update...';
        composer update;
        echo 'Gerando chave da aplicação...';
        php artisan key:generate;
        
        echo 'Aguardando MySQL subir...';
        until mysql -h db -u homestead -psecret -e 'SELECT 1'; do
          echo 'Ainda aguardando...';
          sleep 2;
        done;
        echo 'MySQL disponível, executando migrations...';
        php artisan migrate || true;
        echo 'Iniciando Apache...';
        apache2-foreground;
      "

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pedidocerto
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
